### ISSUE TITLE
Create config from current layout

### ISSUE THREAD

**Issue by varac** [fd0/grobi#15]
It would be nice to have a cmd like `grobi save PROFILENAME` or sth like this that would take current xrandr settings and create a config profile for those. If no config file exist it should get created.

**Comment by Jumziey** [comment]
I was looking into writing a program that works precisely as you describe. But then i found this project in my initial research phase so might just dive into this code base and see if i can't implement that.

Would love to hear from fd0 if there's been any initial work on this, pitfalls or thoughts about the feature.

**Comment by fd0** [comment]
I don't have the time to work on this, it seems rather complicated and I'd like grobi to be a simple tool. Therefore, I'm closing this issue for now. If anybody has an idea on how to implement this without adding too much complexity added to the code base then we can reopen the issue. Please feel free to add further comments!
