### ISSUE TITLE
Document config location

### ISSUE THREAD

**Issue by varac** [fd0/grobi#16]
Where do I need to put the config ?

```
» grobi update
error reading config file: could not find config file
```

**Comment by fd0** [comment]
Ah, it's `~/.config/grobi.conf`, we should add that to the README at least.

**Comment by varac** [comment]
@fd0 Thx! Could you pls change that to `~/.config/grobi/config` or `~/.config/grobi/grobi.conf`, because most configs reside in a subdir of `~/.config`. Or at least recognize if the config file is located in a subdir ?

**Comment by fd0** [comment]
Ah, that'd be a breaking change and I'd like to leave the default (at least for now).

If you'd like to use a custom location for the config file, just run it with `XDG_CONFIG_HOME=$HOME/.config/grobi` or `grobi --config=$HOME/.config/grobi/config` or so.
