### ISSUE TITLE
same-as for mirroring

### ISSUE THREAD

**Issue by desdic** [fd0/grobi#21]
Hi,

I haven't been able to find it but is there a way to mirror a display or will there be support for --same-as xrandr feature ?

**Comment by desdic** [comment]
Actually nevermind I figured out a way :)

**Comment by fd0** [comment]
How did you do it? :)

**Comment by desdic** [comment]
I added a xrandr --output DP-2 --auto --same-as eDP-1 in the execute_after and that works pretty well but I have a small patch ready real soon that just adds a outputs_same_as to the yaml configfile .. just need to apply it and then its ready if you are up for a pull request :)

**Comment by fd0** [comment]
Cool! Just submit the PR, should be a rather small change.

**Comment by desdic** [comment]
PR submitted :)
