### ISSUE TITLE
Version number hard-coded as 0.5.2-dev

### ISSUE THREAD

**Issue by pjones** [fd0/grobi#28]
The `cmd_version.go` file hard codes the version number as `0.5.2-dev`.   Therefore using the `version` command with grobi compiled from the `v0.6.0` tag produces:

```
grobi 0.5.2-dev
compiled with go1.14.9 on linux
```

I'm not sure how golang programs normally deal with this.  If you point me in the right direction I'm happy to open a PR.

**Comment by fd0** [comment]
Oh, thanks for the hint. I've pushed a commit to master which hardcodes `dev` for now.

We used to have a program called `build.go` (pre Go-modules) which sets the version during compilation, but when using `go build` (as it is recommended in the README now) the version is not set so the one from the source is printed.
